- 2.17.50.0.12 - sync patches with Mandriva 2.17.50.0.12-1mdv - implement devel naming policy - implement library provides policy - temporarily make the tests non-fatal because it seems there is a hiccup with   SSP support and one single test (S-records with constructors) which the logs   show as: sr3.cc:(.text+0x24c): undefined reference to `__stack_chk_fail'
git-svn-id: svn+ssh://thor/srv/subversion/annvix/repos/packages@7596 f191e5f7-4e04-0410-925a-985e7dbff663